# Ansible Role: mongodb
# File: /molecule/replicaset-pss-ubi8/group_vars/all.yml
# Description: Managed by doc-sync workflow

---
mongodb_restart_config: true
mongodb_restart_seconds: 5
mongodb_version: 7.0

mongodb_thp: false
mongodb_numa: false

mongodb_replication:
  replSetName: something

mongodb_security:
  authorization: enabled
  keyFile: /etc/keyfile_mongo

mongodb_admin_pass: something
mongodb_adminuser_pass: something

mongodb_net:
  bindIp: 0.0.0.0
  port: 27018

mongodb_systemlog:
  destination: file
  logAppend: true
  path: /opt/somewhere/mongod.log

mongodb_storage:
  dbPath: /opt/mongo/
  journal:
    enabled: true

mongodb_user:
  - database: burgers
    name: bob
    password: 12345
    state: present
    update_password: on_create
