# Ansible Role: mongodb
# File: /molecule/replicaset-psa-ubi8/converge.yml
# Description: Managed by doc-sync workflow

---
- name: Converge
  hosts:
    - test-ubi8-01-v2
    - test-ubi8-02-v2
    - test-ubi8-03-v2
  roles:
    - role: ../..
