# Ansible Role: mongodb
# File: /tasks/install.yml
# Description: Managed by doc-sync workflow

---
- name: install | repo gpg key
  rpm_key:
    key: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
  when: mongodb_repo

- name: install | repo
  yum_repository:
    name: "mongodb-org-{{ mongodb_version }}"
    description: 'MongoDB {{ mongodb_edition }} repo'
    file: mongodb
    baseurl: >-
      https://repo.mongodb.
      {{- (mongodb_edition == 'enterprise') | ternary('com', 'org') -}}
      /yum/redhat/$releasever/mongodb-
      {{- mongodb_edition }}/
      {{- mongodb_version }}/x86_64/
    enabled: true
    gpgcheck: true
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
  when: mongodb_repo

- name: install | group mongod
  group:
    name: mongod
    gid: 28
    system: true

- name: install | user mongod
  user:
    name: mongod
    uid: 28
    system: true
    group: mongod
    comment: 'MongoDB Server'
    home: "{{ mongodb_storage.dbPath }}"
    create_home: false
    shell: /sbin/nologin
  register: set_user

- name: install | dependencies
  dnf:
    name:
      - python3-devel
      - python3-pip

- name: install | mongo edition {{ mongodb_edition }}
  dnf:
    name: mongodb-{{ mongodb_edition }}

- name: install | data folder
  file:
    state: directory
    path: "{{ mongodb_storage.dbPath }}"
    mode: '0770'
    owner: mongod
    group: mongod

- name: install | remove default data folder when set differently
  file:
    state: absent
    path: /var/lib/mongo
  when: mongodb_storage.dbPath != '/var/lib/mongo'

- name: install | remove log folder when set differently
  file:
    state: absent
    path: /var/log/mongodb
  when: >-
    '/var/log/mongodb' not in mongodb_systemlog.path or
    mongodb_systemlog.destination != 'file'

- block:
    - name: install | ensure log folder exists
      file:
        path: "{{ mongodb_systemlog.path | dirname }}"
        state: directory
        owner: mongod
        group: mongod
        mode: '0775'

    - name: install | stat if log file exist
      stat:
        path: "{{ mongodb_systemlog.path }}"
      register: mongodb_log_check

    - name: install | ensure log files exist
      copy:
        content: ""
        dest: "{{ mongodb_systemlog.path }}"
        force: true
        group: mongod
        owner: mongod
        mode: '0755'
      when: not mongodb_log_check.stat.exists

  when: >-
    '/var/log/mongodb' not in mongodb_systemlog.path and
    mongodb_systemlog.destination == 'file'

- name: install | pymongo {{ mongodb_pymongo_version }}
  pip:
    name: pymongo
    executable: pip3
    version: "{{ mongodb_pymongo_version }}"

# Check firewalld status
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Open ports on firewall
  ansible.posix.firewalld:
    port: "{{ mongodb_net.port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  when: ansible_facts['services']['firewalld.service']['state'] == 'running'
