# Ansible Role: mongodb
# File: /molecule/replicaset-pss-ubi8/converge.yml
# Description: Managed by doc-sync workflow

---
- name: Converge
  hosts:
    - replica-ubi8-01
    - replica-ubi8-02
    - replica-ubi8-03
    - replica-ubi8-04
    - replica-ubi8-05
  roles:
    - role: ../..
