# Ansible Role: mongodb
# File: /meta/main.yml
# Description: Managed by doc-sync workflow

---
galaxy_info:
  author: jmrenouard
  description: Ansible role to setup and configure MongoDB
  namespace: jmrenouard
  role_name: mongodb
  version: 1.5.5
  license: Apache License, Version 2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - database
    - mongodb
    - cluster

dependencies: []
