all:
  children:
    mongodb_cluster:
      hosts:
        mongodb-node-1:
          ansible_host: localhost
          ansible_port: 2221
          mongodb_replication_role: primary
        mongodb-node-2:
          ansible_host: localhost
          ansible_port: 2222
          mongodb_replication_role: secondary
        mongodb-node-3:
          ansible_host: localhost
          ansible_port: 2223
          mongodb_replication_role: secondary
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
