# Ansible Role: mongodb
# File: /molecule/default/molecule.yml
# Description: Managed by doc-sync workflow

---
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
provisioner:
  inventory:
    group_vars:
      all:
        mongodb_version: "6.0"
        mongodb_manage_service: false
        mongodb_is_systemd: false
  env:
    ANSIBLE_ROLES_PATH: ../../../:../../
    ANSIBLE_VARS_PLUGINS_ENABLED: host_group_vars,vars_plugin_filter
verifier:
  name: ansible
platforms:
  - name: test-multi-01
    hostname: test-multi-01
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    privileged: true
    pull: true
    volumes:
      - "/var/lib/containerd"
    tmpfs:
      - /run
      - /tmp
    tty: true
    environment:
      container: docker
    pre_build_image: true
    networks:
      - name: test_network
