---
# File: roles/mongod/molecule/default/prepare.yml

- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Clean dnf cache
      ansible.builtin.command: dnf clean all
      changed_when: true
      when: ansible_os_family == 'RedHat'

    - name: Install core utilities
      ansible.builtin.dnf:
        name:
          - sudo
          - procps-ng
          - hostname
          - iproute
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'
