# Ansible Role: mongodb
# File: /molecule/default/host_vars/test-multi-01.yml
# Description: Managed by doc-sync workflow

---
mongodb_thp: false
mongodb_numa: false

mongodb_admin_pass: something
mongodb_adminuser_pass: something

mongodb_user:
  - database: burgers
    name: bob
    password: 12345
    state: present
    update_password: on_create

mongodb_backup:
  enabled: true
  dbs:
    - admin
    - config
    - local
  user: backup
  pass: something
  path: /var/lib/mongodb_backups
  owner: mongod
  group: mongod
  mode: '0660'
  hour: 2
  minute: 5
  day: "*"
  retention: 46  # in hours
